#!/bin/zsh

function cd() {
	if [[ $# -eq 1 && $1 = ...* ]] then
		local a b=''
		a=${(r:(${#1}-1)*3-1::../:)b}
		builtin cd $a
	else
		builtin cd $*
	fi
}

function dimlights() {
	local a
	a=$[($1 / 100) * 22]
	ppower lights:on
	ppower lights:dim:$a
}

function lights() {
	ppower lights:$1
}

function tv() {
	ppower tv:$1
}

function bedtime() {
	ppower lights:on
	ppower monitors:off
	sleep 30
	echo "(SayText \"Goodnight, Christian.\")(quit)" | festival_client
	ppower lights:off
}

function dmalloc {
	eval `command dmalloc -b $*`;
}

function countida {
	grep "default.[Ii][Dd][Aa]" /var/log/httpd/access_log* | wc -l
}

function rmoldthumbs {
	for i in .thumbs/*
	do
		[ ! -e `basename $i` ] && rm $i
	done
}

function cvsdiff {
	cvs -z3 diff -u $* | vim -c "set ft=diff" -
}

function sfget {
	wget `echo $* | sed -e "s/prdownloads/telia.dl/g" -e "s/\?download//g"`
}

function mutt {
	print -Pn "\e]0;mutt\a"
	/usr/bin/mutt
}

#function genthumb {
#	[ ! -e .thumbs ] && mkdir .thumbs
#	for i in *.JPG *.jpg *.jpeg *.gif *.GIF *.png *.PNG; do
#		e
#}
