#!/bin/zsh

function cd() {
	if [[ $# -eq 1 && $1 = ...* ]] then
		local a b=''
		a=${(r:(${#1}-1)*3-1::../:)b}
		builtin cd $a
	else
		builtin cd $*
	fi
}

function calc() {
	echo $* | bc -l
}

function pycd() {
	builtin cd `pywhere "$@"`
}

function buildroot() {
	builtin source ~/buildroots/$1/bin/activate
}

# Limit auto-completion for git, so things aren't super slow.
__git_files () {
    _wanted files expl 'local files' _files
}
